export const turkishCities = [
  'Adana',
  'Adiyaman',
  'Afyonkarahisar',
  'Agri',
  'Aksaray',
  'Amasya',
  'Ankara',
  'Antalya',
  'Ardahan',
  'Artvin',
  'Aydin',
  'Balikesir',
  'Bartin',
  'Batman',
  'Bayburt',
  'Bilecik',
  'Bingol',
  'Bitlis',
  'Bolu',
  'Burdur',
  'Bursa',
  'Canakkale',
  'Cankiri',
  'Corum',
  'Denizli',
  'Diyarbakir',
  'Duzce',
  'Edirne',
  'Elazig',
  'Erzincan',
  'Erzurum',
  'Eskisehir',
  'Gaziantep',
  'Giresun',
  'Gumushane',
  'Hakkari',
  'Hatay',
  'Igdir',
  'Isparta',
  'Istanbul',
  'Izmir',
  'Kahramanmaras',
  'Karabuk',
  'Karaman',
  'Kars',
  'Kastamonu',
  'Kayseri',
  'Kilis',
  'Kirikkale',
  'Kirklareli',
  'Kirsehir',
  'Kocaeli',
  'Konya',
  'Kutahya',
  'Malatya',
  'Manisa',
  'Mardin',
  'Mersin',
  'Mugla',
  'Mus',
  'Nevsehir',
  'Nigde',
  'Ordu',
  'Osmaniye',
  'Rize',
  'Sakarya',
  'Samsun',
  'Sanliurfa',
  'Siirt',
  'Sinop',
  'Sirnak',
  'Sivas',
  'Tekirdag',
  'Tokat',
  'Trabzon',
  'Tunceli',
  'Usak',
  'Van',
  'Yalova',
  'Yozgat',
  'Zonguldak',
]

export const cityPostalPrefixes = {
  Adana: '01',
  Adiyaman: '02',
  Afyonkarahisar: '03',
  Agri: '04',
  Amasya: '05',
  Ankara: '06',
  Antalya: '07',
  Artvin: '08',
  Aydin: '09',
  Balikesir: '10',
  Bilecik: '11',
  Bingol: '12',
  Bitlis: '13',
  Bolu: '14',
  Burdur: '15',
  Bursa: '16',
  Canakkale: '17',
  Cankiri: '18',
  Corum: '19',
  Denizli: '20',
  Diyarbakir: '21',
  Edirne: '22',
  Elazig: '23',
  Erzincan: '24',
  Erzurum: '25',
  Eskisehir: '26',
  Gaziantep: '27',
  Giresun: '28',
  Gumushane: '29',
  Hakkari: '30',
  Hatay: '31',
  Isparta: '32',
  Mersin: '33',
  Istanbul: '34',
  Izmir: '35',
  Kars: '36',
  Kastamonu: '37',
  Kayseri: '38',
  Kirklareli: '39',
  Kirsehir: '40',
  Kocaeli: '41',
  Konya: '42',
  Kutahya: '43',
  Malatya: '44',
  Manisa: '45',
  Kahramanmaras: '46',
  Mardin: '47',
  Mugla: '48',
  Mus: '49',
  Nevsehir: '50',
  Nigde: '51',
  Ordu: '52',
  Rize: '53',
  Sakarya: '54',
  Samsun: '55',
  Siirt: '56',
  Sinop: '57',
  Sivas: '58',
  Tekirdag: '59',
  Tokat: '60',
  Trabzon: '61',
  Tunceli: '62',
  Sanliurfa: '63',
  Usak: '64',
  Van: '65',
  Yozgat: '66',
  Zonguldak: '67',
  Aksaray: '68',
  Bayburt: '69',
  Karaman: '70',
  Kirikkale: '71',
  Batman: '72',
  Sirnak: '73',
  Bartin: '74',
  Ardahan: '75',
  Igdir: '76',
  Yalova: '77',
  Karabuk: '78',
  Kilis: '79',
  Osmaniye: '80',
  Duzce: '81',
}

export function sanitizePostalCode(value) {
  return value.replace(/\D/g, '').slice(0, 5)
}

export function getCityOptions(selectedCity = '') {
  const normalizedCity = selectedCity.trim()

  if (normalizedCity && !turkishCities.includes(normalizedCity)) {
    return [`${normalizedCity} (Existing value)`, ...turkishCities]
  }

  return turkishCities
}

export function getCityOptionValue(option) {
  return option.endsWith(' (Existing value)')
    ? option.replace(/ \(Existing value\)$/, '')
    : option
}

export function isKnownTurkishCity(city) {
  return Boolean(cityPostalPrefixes[city.trim()])
}

export function getCityPostalPrefix(city) {
  return cityPostalPrefixes[city.trim()] || null
}
